services:
  - type: web
    name: qr-url-scanner
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "5000"
